### ISSUE TITLE
Expected prop to be data fetched by Relay

### ISSUE THREAD

**Issue by fenos** [denvned/isomorphic-relay#21] opened 2016-02-15 22:45 UTC
Hi, after i upgraded to `isomorphic-relay v0.5.1` All my components started to complain asking that the data has to be data fetched by relay. 

`Warning: RelayContainer: Expected prop`me`supplied to`Navbar`to be data fetched by Relay. This is likely an error unless you are purposely passing in mock data that conforms to the shape of this component's fragment.`

![screen shot 2016-02-15 at 22 40 18](https://cloud.githubusercontent.com/assets/4754064/13062318/a64aaeb0-d435-11e5-98bd-47b23bed6c86.png)

Any idea about this? After hours of debugging still i couldn't find the reason

**Comment by thelordoftheboards** [comment] 2016-02-15 22:46
I am seeing the same on my project after an upgrade, I did not want to say anything because I thought I just messed up something. So ... +1 I guess?

**Comment by denvned** [comment] 2016-02-16 05:55
@fenos, @thelordoftheboards, thanks for the report. Any ideas on how I can reproduce the error? How your setup is different from the examples (star-wars, todo)? I suppose you have tried to remove the node_modules and do clean install, right? Did v0.5.0 work ok for you?

**Comment by thelordoftheboards** [comment] 2016-02-16 06:18
Let me try to see how I can make it easiest to reproduce for you, I will follow up with you. Clean install after deleting node_modules did not help in my case.

**Comment by thelordoftheboards** [comment] 2016-02-16 06:47
Definitely does not happen with the todo example from isomprohic-relay-router. I will keep digging to find why and where it happens.

**Comment by thelordoftheboards** [comment] 2016-02-16 07:14
As an experiment I tried to modify the todo sample to use exactly the same packages as my project, and it did not cause it to break ... will continue looking.

**Comment by thelordoftheboards** [comment] 2016-02-16 08:10
Here is where my warning comes from:
![image](https://cloud.githubusercontent.com/assets/7056535/13070460/8cea0572-d441-11e5-9217-47ec4eed4742.png)
At this point I do not think it is necessarily related to isomorphic-relay, could be something to do with relay 0.7. I will post more when I find out more.

**Comment by denvned** [comment] 2016-02-16 09:05
@thelordoftheboards, Does the warning show if you comment out the call to `IsomorphicRelay.injectPreparedData`?

**Comment by thelordoftheboards** [comment] 2016-02-16 09:07
I will test that tomorrow. However, if I initially call a page that is not using, for instance, ToDos, and then in the browser navigate to ToDos I see the warnings in the browser console. I would think by that time we would be done with the server rendering.
That said, I will try it anyway.

**Comment by fenos** [comment] 2016-02-16 09:12
@denvned thanks for your promptness and support, I will do trials this evening and try to find out more
@thelordoftheboards thanks to you as well to move forward with debugging

**Comment by fenos** [comment] 2016-02-16 21:53
I tried to remove `IsomorphicRelay.injectPreparedData` but it doesn't seem the problem. I also tried to downgrade to `v.0.50` with no luck.

I can say that my project is more similar to the [Isomorphic-relay-router repo](https://github.com/denvned/isomorphic-relay-router/blob/master/examples/todo/src/), I'm exporting queries as a [playing object](https://github.com/denvned/isomorphic-relay-router/blob/master/examples/todo/src/queries/ViewerQueries.js) and pass them to the routes from the `queires` prop.

**Comment by thelordoftheboards** [comment] 2016-02-17 09:55
Haven't had any time for more detailed troubleshooting, but I noticed that at the same time as this project converted to 7 they added ; after the class definition and before the relay wrapper. I am not sure of the meaning of this ...

https://github.com/ryancole/league/commit/af0c63e2f334aec79cc08b2ece72c466e62d373a

Does it matter?

**Comment by denvned** [comment] 2016-02-17 10:14
> Does it matter?

No, it shouldn't.

**Comment by jkempff** [comment] 2016-02-17 12:55
Just FYI, I'm having the exact same problems, after upgrading to `0.5.1`. The warning also appears on the server side, so `.injectPreparedData` cannot be the cause of the problem.

**Comment by denvned** [comment] 2016-02-17 13:02
@jkempff, sorry you faced it too. Maybe you have any ideas how I can reproduce the error?

@fenos, @thelordoftheboards, @jkempff Maybe any of you can create a small repro project and upload it to GitHub?

**Comment by fenos** [comment] 2016-02-17 13:09
@denvned fair enough, i'll do it this evening when i came back from work if no one would do it before me.
Thanks again

**Comment by thelordoftheboards** [comment] 2016-02-17 20:14
@denvned I tried to reproduce the issue outside of my main project using the ToDo example at no avail. I will prepare my 'full' project with the problem. The size should not be an issue hopefully, the problem is fairly isolated.

**Comment by thelordoftheboards** [comment] 2016-02-18 01:04
@denvned here is my repository: https://github.com/codefoundries/isomorphic-material-relay-starter-kit/tree/develop

Here are the steps to reproduce the problem:
- Clone the `develop` branch locally.
- Run:

```
npm run install
npm run config-local
npm run dev
```
- Navigate to `http://localhost:4444/`.
- Click on top left button in nav bar.
- Choose `Examples`, then `Ensayo`.
- The following message will appear in the console 4 times (for each item):

```
Warning: RelayContainer: Expected prop `Ensayo` supplied to `Ensayo_Item` to be data fetched by Relay. This is likely an error unless you are purposely passing in mock data that conforms to the shape of this component's fragment.
```

I could not make it any simpler than that, my attempts to reproduce it outside of the project so far have been in vain. The same project works perfectly well in 6.1 (`master` branch).

**Comment by denvned** [comment] 2016-02-18 08:02
@thelordoftheboards You forgot to update _babel-relay-plugin-loader_ to version 0.7. With the correct version your repo does not produce the warnings.

As it turned out, it was a user error, so closing for now.

@fenos, @jkempff What version of _babel-relay-plugin_ are you using?

**Closed as completed by denvned** 2016-02-18 08:02 UTC
Labels: usage error

**Comment by thelordoftheboards** [comment] 2016-02-18 08:21
I am sooo dumb. Sorry to waste your time.

**Comment by thelordoftheboards** [comment] 2016-02-18 08:22
Just for everyone else's reference, I will be using npm-check-updates from now on to make sure I am not missing anything. Seems to work fairly well.

**Comment by fenos** [comment] 2016-02-18 11:06
I feel dumb as well :( Thanks denvned to point that thing out, I tried as well to replicate the issue with no luck but that was the cause!! Thanks so much to both of you guys

**Comment by jkempff** [comment] 2016-02-18 15:13
Same here, after updating all dependencies - which was kind of a hassle - everything works as expected!
